Create Unit tests for SpringBoot controller/DAO/service
BUMETCS673/seprojects-cs673olf24team1 pull request #143
Opened 2024-10-07 03:04 UTC by AJun01

2024-10-07 03:29 UTC, battalcevik requested changes
You need to add all dependencies back to pom.xml file please

2024-10-07 03:29 UTC, battalcevik commented on code/backend/course-builder-chatbot-ms/pom.xml
> -	<dependencies>
you have to add back these dependencies on pom.xml file

2024-10-07 03:38 UTC, ananyasingh7 requested changes
Your pom.xml is removing my dependencies!

2024-10-07 03:39 UTC, ananyasingh7 requested changes

2024-10-07 03:39 UTC, ananyasingh7 commented on code/backend/course-builder-chatbot-ms/pom.xml
> -			<groupId>org.springframework.boot</groupId>
DO NOT REMOVE THIS!

2024-10-07 19:12 UTC, igotnowifi-official commented
For Trevor: to review for iteration 3, please ignore for iteration 2 submission. Thank you!

2024-10-11 02:55 UTC, ananyasingh7 requested changes

2024-10-11 02:55 UTC, ananyasingh7 commented on code/backend/course-builder-chatbot-ms/pom.xml
> -		<dependency>
Why is this being deleted?

2024-10-11 02:55 UTC, ananyasingh7 commented on code/backend/course-builder-chatbot-ms/pom.xml
> -	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
Let's not format this, keep it the same

2024-10-11 03:10 UTC, AJun01 commented on code/backend/course-builder-chatbot-ms/pom.xml
> -		<dependency>
it was duplicated, there is a same section at line 33

2024-10-12 21:01 UTC, closed without merging